### ISSUE TITLE
NPCs transporting stuff on paths do not move

### ISSUE THREAD

**Issue by jlc** [widelands/widelands#5678] opened 2022-11-29 21:37 UTC
Hi!

The NPCs on some paths, carrying objects or not, do not move.
The animation of the movement is active, but there are no movements. If objects are carried, they simply never attain the destination flag. 

This behaviour happened even after exiting entirely the game, relaunching it, and reloading the game (which is attached here: 4e.wgf.zip).

I realised it because my buildings were never finished...

**To Reproduce**

Unfortunately, it is not clear how it happened.
An hour or two of playing, saved, played again later, saved, discovered why I was stuck in the game.

**Expected behavior**
The NPCs carrying stuff to arrive at the destination flag ^^

**Screenshots**
Yes, video :)

**Version:**
 - OS: MacOS 13.0 on an Apple M1 MacBook Air 2020
 - Widelands Version:
> Version: 1.1 Release  
> Operating System: MacOS  
> Compiled with SDL version: 2.24.1  
> SDL video driver: cocoa  
> Locale: en  
> Home Directory: /Users/jeanluc/.widelands  
> Configuration File: /Users/jeanluc/.widelands/config  
> Data Directory: /Applications/Widelands.app/Contents/MacOS/data  
> Locale Directory: /Applications/Widelands.app/Contents/MacOS/data/locale  
> Executable Directory: /Applications/Widelands.app/Contents/MacOS/  

*** Last words ***
Thank you so much guys!!! I've just discovered that one of my favorite game of all time is live again! You rock!

https://user-images.githubusercontent.com/24811/204652886-bfadde8d-59c6-41a9-b779-4558307af594.mov

[4e.wgf.zip](https://github.com/widelands/widelands/files/10117542/4e.wgf.zip)

**Comment by hessenfarmer** [comment] 2022-11-29 21:55
Hi, this is not a bug it is a feature of this game. what you see in the video is what we call a traffic jam. Managing your road system to avoid such situations is one of the key skills you need to master.      
It is arising when from one side of a flag more wares are arriving then on the other side can be transported to the next one.  As each flag can only hold 8 items the carrier will not move there until one slot is free.    
especiall dangerous are intersection flags where 3 ore more roads meet. In your case the one at the bottom of the video.    
Solutions are to divert ware streams by buiding warehouses, build second carrier farms (ox, horse, donkey, reindeer, tapir) to get a second carrier on busy roads, build roads in a manner that a maximum number of flags can be placed (i.e. a flag every 2 fields) or build more roads. and avoid critical intersections.      
So I will close this as won't fix.

**Closed as completed by hessenfarmer** 2022-11-29 21:55 UTC
Labels: question, wontfix

**Comment by jlc** [comment] 2022-11-29 21:58
🙏
Thank a lot for explanations 😌 Happy that's not a bug ^^
