### ISSUE TITLE
cant run new a game  after setup

### ISSUE THREAD

**Issue by jcy1001** [widelands/widelands#5464] opened 2022-07-02 06:34 UTC
[00:16:22.323 real] ERROR: ##############################
[00:16:22.323 real] ERROR:   FATAL EXCEPTION: Error while loading tribe 'barbarians': [../src/scripting/lua_errors.cc:22] tribe barbarians: Failed adding immovable 'wheatfield_tiny': [../src/scripting/lua_errors.cc:22] wheatfield_tiny: Error in immovable program main: Error reading line 'animate=idle duration:30s': basic_string::append
[00:16:22.323 real] ERROR: stack traceback:
[00:16:22.323 real] ERROR: 	[string "tribes/immovables/wheatfield/tiny/init.lua"]:5: in main chunk
[00:16:22.323 real] ERROR: 	[C]: in method 'new_tribe'
[00:16:22.323 real] ERROR: 	[string "tribes/initialization/barbarians/units.lua"]:10: in main chunk
[00:16:22.323 real] ERROR: stack traceback:
[00:16:22.323 real] ERROR: 	[string "tr
[00:16:22.323 real] ERROR: ##############################
[00:16:22.323 real] ERROR:   Please report this problem to help us improve Widelands.
[00:16:22.323 real] ERROR:   You will find related messages in the standard output (stdout.txt on Windows).
[00:16:22.323 real] ERROR:   You are using build 1.0 (Release).
[00:16:22.323 real] ERROR:   Please add this information to your report.
[00:16:22.323 real] ERROR:   If desired, Widelands attempts to create an emergency savegame.
[00:16:22.323 real] ERROR:   It is often – though not always – possible to load it and continue playing.
[00:16:22.323 real] ERROR: ##############################
[00:16:37.786 real] INFO: SoundHandler: Closing 1 time, 22050 Hz, format 32784, 2 channels
[00:16:37.786 real] INFO: SoundHandler: SDL_AUDIODRIVER wasapi

**Comment by Noordfrees** [comment] 2022-07-02 07:41
- Which add-ons are enabled?
- Which map, which tribes, and which starting conditions are you using?
- Did it work previously and stopped working now, or is this a fresh installation and has never worked?

**Comment by jcy1001** [comment] 2022-07-02 07:45
no add-ons  ,   I just fresh installation , I try select single map player , editor ,all cant run ,     I try resinstalll  ,but still cannt run
![image](https://user-images.githubusercontent.com/24226340/176991731-54b1fc69-4fdb-46b5-a501-080f9ca00deb.png)

**Comment by jcy1001** [comment] 2022-07-02 07:45
no add-ons , I just fresh installation , I try select single map player , editor ,all cant run , I try resinstalll ,but still cannt run

**Comment by frankystone** [comment] 2022-07-02 17:25
- An which widelands version are you using?
- Which operating system?
- Is this the first installation of widelands?

The bug report template is there on purpose...

**Comment by jcy1001** [comment] 2022-07-03 00:38
version 1.0
windows10
first installtion




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月3日(星期天) 凌晨1:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [widelands/widelands] cant run new a game  after setup (Issue #5464)





  
An which widelands version are you using?
 
Which operating system?
 
Is this the first installation of widelands?
  
The bug report template is there on purpose...

**Comment by frankystone** [comment] 2022-07-03 08:15
I guess you are playing with Chinese language?

Please try to set "English" as language in `Options→Interface` and check if the error still occurs.

Maybe related: #5211

**Comment by jcy1001** [comment] 2022-07-03 08:18
yes thanks bro



发自我的iPhone


------------------ Original ------------------
From: kaputtnik ***@***.***&gt;
Date: Sun,Jul 3,2022 4:15 PM
To: widelands/widelands ***@***.***&gt;
Cc: jcy1001 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [widelands/widelands] cant run new a game  after setup (Issue#5464)





 
I guess you are playing with Chinese language?
 
Please try to set "English" as language in Options→Interface and check if the error still occurs.
 
Maybe related: #5211

**Comment by frankystone** [comment] 2022-07-05 16:34
I think this is a duplicate of #5211 

@jcy1001 : If the Error is still present with other non-asiatic languages, please reopen this bug report.

**Closed as completed by frankystone** 2022-07-05 16:34 UTC
Labels: bug, duplicate, needs information
