### ISSUE TITLE
BOOST_HEADER_DEPRECATED

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4556] opened 2020-12-12 12:08 UTC
Just got a lot of this pragma messages with boost version 1.74.0-2

~~~~
In Datei, eingebunden von /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 von /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 von /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 von /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 von /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 von /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 von /usr/include/boost/shared_ptr.hpp:17,
                 von /usr/include/boost/signals2/signal.hpp:21,
                 von /home/kaputtnik/Quellcode/widelands-repo/widelands/src/logic/map_objects/map_object.h:23,
                 von /home/kaputtnik/Quellcode/widelands-repo/widelands/src/economy/economy.h:29,
                 von /home/kaputtnik/Quellcode/widelands-repo/widelands/src/wui/economy_options_window.h:25,
                 von /home/kaputtnik/Quellcode/widelands-repo/widelands/src/wui/economy_options_window.cc:20:
/usr/include/boost/function_output_iterator.hpp:14:1: Anmerkung: »#pragma message: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.«
   14 | BOOST_HEADER_DEPRECATED("<boost/iterator/function_output_iterator.hpp>")
~~~~

**Version:**
 - OS: archlinux
 - Widelands Version: [91caec3@master](Debug)

**Comment by Noordfrees** [comment] 2020-12-12 12:59
Duplicate of https://github.com/widelands/widelands/issues/4234#issuecomment-742807151

Some of the CI builds also show this

**Comment by hessenfarmer** [comment] 2021-01-11 08:47
boost 1.75 fixed it

**Closed as completed by hessenfarmer** 2021-01-11 08:47 UTC
Labels: bug, duplicate, building & packaging
