### ISSUE TITLE
Game crash when reading the message that an expedition is ready.

### ISSUE THREAD

**Issue by Wegge** [widelands/widelands#4248] opened 2020-09-10 12:00 UTC
[Imminent.zip](https://github.com/widelands/widelands/files/5201381/Imminent.zip)

Please fill out the relevant sections below and delete the rest.

**Describe the bug**
When opening the notification that en expedition is ready, a crash occurs.

**To Reproduce**
1. Load the attached save file.
2. Wait for the ship to complete, and the notification that the expedition is ready.
3. Open the Message window

**Expected behavior**
I expect to be told that the expedition is ready. Instead my world crash and burn :(

**Version:**
- OS: Fedora 32
- Widelands 1.0~git24875[ff36ede@master]

**Comment by Niektory** [comment] 2020-09-10 14:16
Probably a duplicate of #4210

**Closed as completed** 2020-09-11 10:27 UTC
Labels: bug, duplicate, crashes or hangs
