### ISSUE TITLE
Segfault opening wares statistics

### ISSUE THREAD

**Issue by pabordel** [widelands/widelands#4222] opened 2020-09-05 13:24 UTC
A segfault happens each time I press "p" or use the menu  to see wares statistic 
os : ubuntu 20.04
saved game :
[en cours.wgf.zip](https://github.com/widelands/widelands/files/5178122/en.cours.wgf.zip)

widelands output :
[widelands.log.zip](https://github.com/widelands/widelands/files/5178125/widelands.log.zip)

**Comment by Noordfrees** [comment] 2020-09-05 13:26
Duplicate of #4172

**Closed as completed** 2020-09-06 08:26 UTC
Labels: bug, duplicate, crashes or hangs, statistics
