### ISSUE TITLE
AI dismantles military site while also building same type right next to it

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5424] opened 2022-05-15 00:00 UTC
**Describe the bug**
While testing the atl02 scenario, I've once caught the AI dismantling a fortress right on the border while building another one, so I was able to conquer this area by quickly building some guardhouses. Here's the save with the dismantle:
[atl2_ai_fortress.wgf.zip](https://github.com/widelands/widelands/files/8694058/atl2_ai_fortress.wgf.zip)

Later to the East of here it lost quite a bit of land to me because it kept dismantling its military sites.

**Expected behavior**
The AI should not build and dismantle costly buildings next to each other, and it should be more careful not to dismantle military sites without backup.

**Screenshots**
![ai_fortress](https://user-images.githubusercontent.com/80712255/168451528-035f88d3-1111-4781-876b-835aebfaf91f.png)

**Version:**
 - OS: Debian oldstable
 - Widelands Version: 1.1~git25741 (0ce5fb6@master) (Release) (I was too lazy to rebuild for scenario PR branch)

**Comment by tibor95** [comment] 2022-05-15 11:31
This is controlled by genetic algorithm but I agree, it is suboptimal...

**Comment by tothxa** [comment] 2022-05-15 13:14
I forgot to mention that this is the stage of the scenario when we can't attack each other, so I guess, from the AI's point of view we are allies. I don't know how that is handled, whether it can "think" that I won't take advantage of the situation. But even then, some of its dismantles resulted in immediate land loss because of already existing military sites on my side.

**Comment by tibor95** [comment] 2022-05-15 19:10
No, AI for sure do not consider the other player as ally. Probably it just concluded that it is safe to dismantle as there are no potential attackers. And new militarysite is being built in vicinity...
Definitely there is no such logic that would estimate when own site will be built and how fast the enemy can built any smallest site.
Another reason for aggressive dismantlement might be shortage of own soldiers...
Generally the logic is just fuzzy.

**Comment by hessenfarmer** [comment] 2022-05-16 09:32
this is one very old bug see #1083 which I couldn't track down to its root cause completely.
due to being a duplicate to #1083 I'll close this one.

**Closed as completed** 2022-05-16 12:52 UTC
Labels: bug, duplicate, question, military, ai
