### ISSUE TITLE
Segfault after port is lost

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#3683] opened 2020-02-09 01:50 UTC
Ubuntu 19.10. Widelands Version r24412[b0849ef@master] (Release). Using a later version results in a crash on loading the save but that's another matter (or may be expected?)

The port at the current window location has just been lost. Boo. Speed up the game and shortly it will segfault:

```
MO(11514,empire_recruit): [fugitive]: wander randomly
MO(5765,empire_ship): pop_destination(5640): rerouted to portdock 6890 (carrying 0 items)
MO(5765,empire_ship): push_destination(4759): rerouted to portdock 6890 (carrying 0 items)
22862 Segmentation fault      (core dumped)

```
[Savegame.zip](https://github.com/widelands/widelands/files/4176360/Savegame.zip)
[Tasmanian Black War.zip](https://github.com/widelands/widelands/files/4176361/Tasmanian.Black.War.zip)

**Comment by Noordfrees** [comment] 2020-02-09 11:24
Can reproduce:
~~~~
widelands: /home/benedikt/wl/scenario-editor/src/economy/portdock.cc:396: void Widelands::PortDock::load_wares(Widelands::Game&, Widelands::Ship&): Assertion `dest' failed.
~~~~
Seems to be a duplicate of #3544

**Closed as completed** 2020-06-06 08:53 UTC
Labels: bug, duplicate, crashes or hangs, seafaring, urgent
