### ISSUE TITLE
Game crashes when loading a corrupt save

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#4576] opened 2020-12-30 14:58 UTC
**Describe the bug**
The error message box when loading an invalid save got lost during #4518. Instead the game crashes.

**Version:**
 - Widelands Version: since `d9a2b830552cc15afb30da77d9b5df6cec37babc`

**Comment by Noordfrees** [comment] 2020-12-30 15:17
I have manipulated a savegame so it fails to load, but the only result is that I bounce back to the main menu with no error message (which I'll fix). 
Can you attach a corrupt savegame and describe steps to reproduce the crash?

Edit: Ok sometimes I get an assert fail but not reproducible…
Edit2: Looks like the long jumps by exception catching are messing up the Panel::modal_ stacking

**Comment by Noordfrees** [comment] 2020-12-30 15:40
The issue was actually quite simple – a piece of code that is meant to be run only once being run twice by accident…
Fixed in #4572

**Closed as completed** 2021-01-03 11:36 UTC
Labels: bug, crashes or hangs, ui, regression
