### ISSUE TITLE
2nd Barbarian mission: Some essential Buildings not available

### ISSUE THREAD

**Issue by m0nk33** [widelands/widelands#3790] opened 2020-03-22 09:58 UTC
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
In the 2nd Barbarian mission some essential Buildings are not available/cannot be build. E.g. farms to support mines, etc. 

**To Reproduce**
1. Start 2nd Barbarian Mission
2. Build stuff
3. See that buildings are not available

**Expected behavior**

**Screenshots**

**Version:**
 - OS: win10
 - Widelands Version: Build 20 (Release)

**Comment by frankystone** [comment] 2020-03-22 12:32
Can't reproduce.

Are you sure you have solved the objectives? Some buildings are only available if specific objectives get solved.

**Comment by m0nk33** [comment] 2020-03-22 15:54
You are right, I never build a Rangers Hut because I thought I wont need one (huge forest). Still was able to finish the mission though. Maybe it makes sense to change the mission accordingly. 

Thanks. Closing it.

**Comment by gunchleoc** [comment] 2020-03-25 07:39
If you're getting stuck, others will get stuck too. I think we should add a list of buildings to the objective.
```

         barbarians_lumberjacks_hut = 1,
         barbarians_rangers_hut = 1,
         barbarians_quarry = 1,
         barbarians_wood_hardener = 1,
```

**Comment by gunchleoc** [comment] 2020-03-25 08:36
Actually, we are already listing the required buildings in the objective, so I'm closing this again.

**Closed as completed by gunchleoc** 2020-03-25 08:36 UTC
Labels: enhancement, good first issue, lua, campaigns & scenarios
