### ISSUE TITLE
'Terminate employment' should not require manual selection of the only worker.

### ISSUE THREAD

**Issue by karadoc** [widelands/widelands#6196] opened 2023-10-21 06:59 UTC
**Is your feature request related to a problem? Please describe.**
When I want to 'terminate employment' of a worker in a building, I have to select the worker before pressing the button - even if there is only one worker. Sometimes this is a bit confusing, because clicking the 'worker' button at the top can make it look like the worker is selected, but they still won't leave. Whereas if I do select the worker, and then deselect them by clicking somewhere else, they will still be evicted when I click the button.

**Describe the solution you'd like**
Clicking the 'terminate employment' button should evict a worker even if none has been selected yet. Currently, if I select and then deselect a worker, it still evicts them. My suggestion is that when the building window is opened, the game behaves as though the 'previously selected' worker is just whoever is on top of the list - so that opening the window and clicking 'terminate employment' will evict the top worker on the list.

**Describe alternatives you've considered**
It doesn't have to be the top worker of course. It could be the last if you think that makes more sense. Or maybe only 'automatically' select the worker to evict in cases where there is only one worker present.

**Implementation steps**
 * Build a woodcutter and wait for the worker to arrive.
 * Click the building to open the building's window.
 * Click 'terminate employment of selected worker'.

(Currently this will do nothing, because we did not select the worker. My suggestion is that it terminates the employment of the only worker present even if we didn't manually select them.)

**Comment by SimonHeimberg** [comment] 2023-11-05 10:58
This is fixed for 1.2 since 86b93962b8, see also GH #5515

**Comment by tothxa** [comment] 2023-11-05 11:50
Duplicate of #4887

**Closed as completed** 2023-11-05 11:49 UTC
Labels: duplicate, enhancement, good first issue
