### ISSUE TITLE
Map "Desert Tournament" is imbalanced

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#3955] opened 2020-06-27 16:59 UTC
**Describe the bug**
The Map data/maps/Desert_Tournament.wmf is imbalanced. Blue and red player have a much faster acces to the central part of the map compared to the other teams

**To Reproduce**

Check the Replay https://www.widelands.org/forum/attachment/f714a75da2830b9531de4add2dd12a3f569a1599/ based on https://www.widelands.org/forum/topic/4847/?page=15#post-33651. This shows the Issue quite clearly.

**Expected behavior**
All Players / Sugested Teams have equal changes to reach the center of the map,

**Replay**
TODO  king_of_nowhere

**Version:**
 r24644[1e2bab5@HEAD] (amazones)

**Comment by Noordfrees** [comment] 2020-08-16 10:20
Closing as duplicate of #967

**Closed as completed by Noordfrees** 2020-08-16 10:20 UTC
Labels: bug, duplicate, maps
