### ISSUE TITLE
Crash when cancelling expedition in discovery mode

### ISSUE THREAD

**Issue by markusu49** [widelands/widelands#4642] opened 2021-01-25 13:11 UTC
The game crashes when cancelling an expedition in discovery mode. Full log and savegame attached.

OS: Manjaro Linux
Widelands Version: Build 21

```
[../src/wui/seafaring_statistics_menu.cc:197] Unreachable code was reached.
```

**To reproduce**

Load attached savegame and try to cancel one of the two remaining expeditions.

**Maybe related**

Game saving stops working after a while in this game situation:

```
GenericSaveHandler::save_file: data could not be written to file save/2021-01-25T13.47.32.wgf: Player 3: economy 14 has no representative
```

**Attachments**

[log.txt](https://github.com/widelands/widelands/files/5866677/log.txt)
[game.zip](https://github.com/widelands/widelands/files/5866695/game.zip)

**Comment by Noordfrees** [comment] 2021-01-25 13:15
This seems to be a duplicate of #4608
fixed in the current development version by #4609

**Closed as completed by Noordfrees** 2021-01-25 13:15 UTC
Labels: bug, duplicate, crashes or hangs, statistics, seafaring
