### ISSUE TITLE
Savegame from replay not shown in loading menu

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3945] opened 2020-06-14 19:38 UTC
A savegame that was created from a replay is not shown in the list od loadable savegames (singleplayer or multiplayer). However it is loadable with doubleclick directly from the filesystem. 

see also https://www.widelands.org/forum/post/33535/

to reproduce: choose a replay , save , open e.g sngleplayer-load game , Go to .widelands/save and see the file created , doubleclick 

Version was amazons-7461
75189d8c2182065599fa0f72ee56737f4f644ed6

**Comment by Noordfrees** [comment] 2020-06-14 19:56
Confirmed on current master (3a98a0bfec8c7519bbdac8520626b36d67f9d7fe)

**Comment by Niektory** [comment] 2020-06-14 20:42
It's like this since #3748. Before that was merged savegames saved from replays were loadable from the multiplayer load screen (but not from the singleplayer screen).

**Comment by hessenfarmer** [comment] 2020-06-16 06:23
As the workaround only works if the player has chosen the save compressed option, this is a candidate for having it fixed in the RC if possible with minimum risk. 
I will try to test the same with the open branch of @jmoerschbach

**Comment by hessenfarmer** [comment] 2020-06-18 07:21
According an updated forum post this is more severe as saves from local network games seem to be not loadable as well.
Needs to be confirmed though

**Comment by Noordfrees** [comment] 2020-06-18 08:52
I cannot confirm that. Starting a new LAN game, saving it, restarting Widelands, choosing LAN → saved game, I am offered the new savegame as expected.

**Comment by jmoerschbach** [comment] 2020-06-18 19:58
> 
> 
> As the workaround only works if the player has chosen the save compressed option, this is a candidate for having it fixed in the RC if possible with minimum risk.
> I will try to test the same with the open branch of @jmoerschbach

Hi,

sry, I see this only now...
There will be no different behaviour in #3847 since this not touched at all in that branch.

I'm quite sure I introduced this behaviour more or less intentionally - see https://github.com/widelands/widelands/pull/3748#issuecomment-602854920

As it happens, I'll have time tomorrow to look into this and hopefully can present a quick fix
The question of that time still stands actually:
How do I actually create replays?

**Closed as completed** 2020-06-20 08:51 UTC
Labels: bug, saveloading & compatibility, replay
