### ISSUE TITLE
Game interface is drawn in a wrong place

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4160] opened 2020-08-24 23:26 UTC
Reported by @frankystone. I can't reproduce so far but I've seen this problem before. It happens when the surface the game draws on is different size than the window. Normally they should stay synchronized but apparently they do not in some cases. One case I know was problematic was when the game tried to resize a maximized window, but I thought I took care of it (by forcibly unmaximizing it before resize).

@frankystone On what OS does it happen? Is the window maximized at any point? Is the window being resized by any other means than the options screen? If you can reproduce it again can you post a screenshot of the entire window (and the exact steps that led there)?

Note: If the "Use system mouse cursor" option is disabled, then the cursor will also be drawn in a wrong position, but in sync with the interface, so the bug will be harder to notice.

**Version:** happens on #4080 and on master

**Original report:**

I used to start at resolution 1920x1080. If i set the resolution to 800x600 and reset it to 1920x1080 back, the mouse pointer do not 'grab' the buttons and the entries in the dropdowns correctly: I have to click at the bottom or below the buttons/dropdown-entries to trigger a click. Best noticeable in conjunction with the tooltips: They appear also at the bottom or below the button/dropdown-entries.

Hm, difficult to explain and difficult to reproduce. Try following:

1. Set 800x600 resolution in options and click Apply
2. Open Options again and set resolution back, but click on Cancel
3. Open Options again and set your preferred resolution and click on apply

Then hover over the buttons. The corresponding tooltip does not appear if the mouse pointer is on the top of the button. It appears only if the mouse pointer is on half height of the button. You can't make a click at the top of the buttons, only there where the tooltip appears. It feels like the button is moved down, like shown here:

![screenshot](https://user-images.githubusercontent.com/6730556/91078552-194e9880-e643-11ea-8d0f-b192d7e1633c.png)

The position of the mouse pointer shows no tooltip. Only if i move the mouse a bit down (into the red marked area). And clicking do also only work in this red area. In this state the buttons of submenus are also not clickable, one has to click on the bottom window border to trigger the click.

The mouse pointer is below the button and one can trigger a click here:

![screenshot](https://user-images.githubusercontent.com/6730556/91080193-764b4e00-e645-11ea-86d6-21ce0d1825ab.png)

**Comment by frankystone** [comment] 2020-08-25 06:49
OS: archlinux
Version is: 7ee32e9@master] (Debug)

My monitor setup:
~~~~
$:> xrandr
Screen 0: minimum 8 x 8, current 3600 x 1080, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  59.94    50.00    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.93    59.94  
HDMI-0 connected 1680x1050+1920+15 (normal left inverted right x axis y axis) 470mm x 300mm
   1680x1050     59.88 +  59.95* 
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94
~~~~

Starting  widelands in window mode (it starts at primary monitor with resolution 1920x1080) i noticed the following:

1. Options shows me an active resolution of 1912x1047
2. Set resolution 1920x1050 and click Accept. The screen flickers a bit caused by some relayouting of the ui elements

Now the misbehavior happens. The OK button of the options screen can be clicked below the visual image. The main menu looks like shown below (notice the position of the tooltip). Closing widelands, assuming the resolution i set is stored, and starting widelands again the options shows the resolution in 1. again and i can reproduce the issue with step 2.

![moved_buttons](https://user-images.githubusercontent.com/6730556/91130940-bdb8f500-e6ac-11ea-8b71-63c6fafed7af.jpg)

Some resolutions set in widelands are not exactly the same when restarting widelands. E.g. set 1680x1050 in options, restart widelands and the options shows me 1680x1051.

**Comment by frankystone** [comment] 2020-08-25 06:59
Now i have managed to get the following:

![moved_buttons_1](https://user-images.githubusercontent.com/6730556/91142478-1e4a3100-e6b1-11ea-8db7-f7b341a8a078.jpg)

The whole menu including the background image was shifted down.

**Comment by frankystone** [comment] 2020-08-25 07:03
Seems like only the x-axis is affected.

Bullshit, it's the y-axis... sorry

**Comment by Niektory** [comment] 2020-08-25 13:54
Gah. I still can't reproduce even after replicating your monitor setup.

Could you run this branch, reproduce the bug and post the log output? https://github.com/Niektory/widelands/tree/resolution_debug

**Comment by frankystone** [comment] 2020-08-25 16:16
I noticed also some flickering when hitting a mouse button in the first splashscreen ("Press any key to continue"). It feels like the window get translucent, or get closed and immediately reopened again. This last just miliseconds.

Here you are, the attached file shows the output after reproducing the bug. This is the output directly after start at resolution 1980x1080 until the first splashscreen appears:

~~~~
**** END SOUND REPORT ****
++ refresh_graphics()
++ change_resolution(): 1912x1047 to 1912x1047; resize_window=true
++ set_window_size(): attempting resize 1912x1047 to 1912x1047
++ set_window_size(): resized to 1912x1047
++ resolution_changed(): old 1912x1047; new 1912x1047
++ refresh_graphics()
++ change_resolution(): 1912x1047 to 1912x1047; resize_window=true
++ set_window_size(): attempting resize 1912x1047 to 1912x1047
++ set_window_size(): resized to 1912x1047
++ resolution_changed(): old 1912x1047; new 1912x1047
++ SDL_WINDOWEVENT_SIZE_CHANGED: 1920x1051
++ SDL_WINDOWEVENT_RESIZED: 1920x1051
++ change_resolution(): 1912x1047 to 1920x1051; resize_window=false
++ resolution_changed(): old 1912x1047; new 1920x1051
++ refresh(): window size 1920x1051
~~~~

And after clicking the splashscreen away:

~~~~
++ refresh_graphics()
++ change_resolution(): 1920x1051 to 1920x1051; resize_window=true
++ set_window_size(): restoring window from 1920x1051
++ set_window_size(): restored window to 1920x1051
++ set_window_size(): attempting resize 1920x1051 to 1920x1051
++ set_window_size(): resized to 1912x1047
++ resolution_changed(): old 1920x1051; new 1912x1047
Initializing economy serial
lastserial: 0
++ SDL_WINDOWEVENT_SIZE_CHANGED: 1912x1047
++ SDL_WINDOWEVENT_RESIZED: 1912x1047
++ change_resolution(): 1920x1051 to 1912x1047; resize_window=false
++ resolution_changed(): old 1912x1047; new 1912x1047
++ refresh(): window size 1912x1047
~~~~
[resolution_log.txt](https://github.com/widelands/widelands/files/5124946/resolution_log.txt)

**Comment by frankystone** [comment] 2020-08-25 16:42
Just to mention it: I do not resize the window, just start the game and clicked on Options and the corresponding dropdowns/buttons (Accept/OK).

**Comment by frankystone** [comment] 2020-08-25 18:00
I've made a screencast of the issue. You can find it here: https://c.1und1.de/@520176427140645159/jGX8y6RKRgGpzvOm7ok5eQ

Note the following:
* The resolution shown in options menu
* The adjustments of ui elements if i set the resolution to 1920x1080
* The misaligned tooltips (=area to click) in the options menu
* The tooltips are now beneath the mouse pointer
* I have to click below the buttons
* After reopening the options again and uncheck "Use System mouse pointer" and click on "Accept" all is working fine again. I had trouble to find the correct mouse pointer position, so first i have checked "Grab mouse" :-D

**Comment by Niektory** [comment] 2020-08-25 19:42
Thanks for the screencast, it's super helpful. It's indeed the same issue that I ran into myself. Except on my system it only happened when the window was maximized, so I worked around it by unmaximizing the window before resizing. Unfortunately on your system it happens even when it's not maximized.

Basically what happens is that I call *SDL_SetWindowSize()* to resize the window to the new size but it's not actually resized to that size. In this case it's probably because the new size together with the window decorations would be larger than the screen and the window manager (or something else) doesn't like that. The worst part is, we don't know that it failed because SDL loses touch with reality and *SDL_GetWindowSize()* now happily reports the size which we tried to resize to instead of the real one.

I'll see if I can find a workaround that works. If not I'll have to remove some functionality...

**Comment by frankystone** [comment] 2020-08-25 20:52
hm... why does it work just after starting widelands? In this state the ui  does not have this issue. So if it works correct after starting widelands, and not working correct after applying a resolution, there must be different calculations?

**Comment by Niektory** [comment] 2020-08-25 21:53
Here's the sequence of events. Note that all sizes are the sizes of the *contents* of the window; they do not include window decorations (title bar and borders).
- Widelands is started.
- Widelands creates a window at size **1920x1080**.
- The system maximizes the window to **1920x1051** (full screen minus title bar). Widelands receives *SDL_WINDOWEVENT_SIZE_CHANGED* and *SDL_WINDOWEVENT_RESIZED* events with the size **1920x1051**, *SDL_GetWindowSize()* reports size **1920x1051** and Widelands resizes its UI to match it.
- The user skips the intro. At the main menu Widelands refreshes the graphics and unmaximizes the window in the process. Widelands receives *SDL_WINDOWEVENT_SIZE_CHANGED* and *SDL_WINDOWEVENT_RESIZED* events with the size **1912x1047** (full screen minus title bar and borders), *SDL_GetWindowSize()* reports size **1912x1047** and Widelands resizes its UI to match it.
- The user opens the options screen. The current window size **1912x1047** is displayed in the dropdown.
- The user changes the size in the dropdown to **1920x1080** and clicks *Apply*.
- Widelands attempts to resize the window to **1920x1080**. Widelands receives an *SDL_WINDOWEVENT_SIZE_CHANGED* event with the size **1920x1080**, *SDL_GetWindowSize()* reports size **1920x1080** and Widelands resizes its UI to match it. However, the window is not actually resized and stays at **1912x1047**, so Widelands now draws the UI at the wrong size.

So, to answer your question: When starting Widelands we create a window at the desired size, which works, and the system may resize it and notify us about it, which also works. When applying a resolution we (try to) resize it ourselves – this (in some cases) fails.

**Comment by Niektory** [comment] 2020-08-25 22:22
I've got an idea that is a little silly. Could you try the debug branch again and see if it behaves differently?

**Comment by frankystone** [comment] 2020-08-26 05:46
Thanks for the explanation :-)

The issue is gone, but the window (including title bar and borders) is now bigger than the screen: The title bar is at the top, but the bottom is below the bottom of the screen. The text of the splashscreen and the images in the bottom corners are too far down.

![resolution](https://user-images.githubusercontent.com/6730556/91257604-a5a7ab00-e76a-11ea-95ef-522f9eba2c03.jpg)

What if the list of resolution get enhanced like "1920x1080 (1920x1051)" and the Tooltip get enhanced to something like "Window size (window size minus borders)". This way it is more understandable what this values means. Resizing to the maximum should be prevented then, respectively leads to the same resolution (1920x1051)

My windowmanager (kwin) gives me also the option to display a window without borders. Didn't tested it yesterday, but i think then the issue wouldn't be present. But in this state i can't get the borders back without closing widelands, because some global system hotkeys do not work with widelands. Especially ALT+F4 (close window) or ALT+F3 (window options). But that's another issue.

**Comment by Niektory** [comment] 2020-08-26 11:23
Here's how I see it: I think the possibility to resize the window by dragging the borders and using window manager controls makes the "Window Size" dropdown mostly obsolete. The dropdown is left there for the cases where you really want a specific UI size – taking screenshots or testing UI scaling, these kinds of things. I think the dropdown should be optimized for these use cases, because for others there's no need to use it.

So I would keep the behavior as it is. AFAIK detecting the size of window decorations can't be done on all platforms so let's not go there.

**Comment by gunchleoc** [comment] 2020-08-26 13:00
I think we should keep it. One sometimes needs a specific resolution, e.g. I like to revert to 800x600 for testing purposes without doing lots of fiddly corner dragging. Speaking of fiddly corner dragging, it's also an accessibility feature for people who have low dexterity in their hands.

**Comment by frankystone** [comment] 2020-08-26 16:46
> I think the dropdown should be optimized for these use cases, because for others there's no need to use it.

> So I would keep the behavior as it is. AFAIK detecting the size of window decorations can't be done on all platforms so let's not go there.

Yes. If possible the dropdown should only show available resolutions given by the graphics driver. AFAIK on startup widelands read the set resolution from the config file and the dropdown should show this information. If the real size (inside the borders) is a bit smaller, i guess no one would ever notice it.

**Comment by Niektory** [comment] 2020-08-27 15:41
What do you think about:

![Maximized in dropdown screenshot](https://user-images.githubusercontent.com/4470900/91463697-fd8a0300-e88b-11ea-9a86-71f71023e93d.png)

Or, going even further:

![Fullscreen in dropdown screenshot](https://user-images.githubusercontent.com/4470900/91463711-0084f380-e88c-11ea-8216-01ba86226242.png)

(this one would replace the checkbox)

**Comment by Noordfrees** [comment] 2020-08-27 15:52
+1 for the second one :)

edit: might be hard to integrate this with fixing #4151 though

**Comment by frankystone** [comment] 2020-08-27 19:53
I think both are good :-)

**Closed as completed** 2020-09-09 01:16 UTC
Labels: bug, graphics, ui
