### ISSUE TITLE
[Duplicate] Widelands::Bob::State& Widelands::Bob::top_state(): Assertion `stack_.size()' failed

### ISSUE THREAD

**Issue by PinPhreek** [widelands/widelands#4235] opened 2020-09-07 15:28 UTC
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
I played on the newest version of the master-branch (details below). And suddenly my game froze and crashed

**To Reproduce**
I have no Idea.

**Version:**
 - OS: Arch Linux 5.4.62-1-lts
 - Widelands Version: Widelands Build 1.0~git39[6307961@master](Debug)

**Error**
2:30:57.364 DEBUG: TW(1859): destination disappeared or economy mismatch -> fail
widelands: ../src/logic/map_objects/bob.h:301: Widelands::Bob::State& Widelands::Bob::top_state(): Assertion `stack_.size()' failed.
Aborted (core dumped)

[world_save.zip](https://github.com/widelands/widelands/files/5183805/world_save.zip)
(Save created in release-build 21)

**Comment by Noordfrees** [comment] 2020-09-07 15:48
Duplicate of #3669

Do you have a replay?

**Comment by PinPhreek** [comment] 2020-09-07 15:57
[replay.zip](https://github.com/widelands/widelands/files/5183930/replay.zip)

**Comment by Noordfrees** [comment] 2020-09-07 17:11
Strangely enough I cannot reproduce with the same version and the replay :( 
Perhaps the bug is somewhere in rendering/ui-related code…

**Comment by PinPhreek** [comment] 2020-09-07 17:36
I couldn't it reproduce neither :(

**Closed as completed** 2020-11-11 05:12 UTC
Labels: bug, duplicate, crashes or hangs, non-reproducable
