### ISSUE TITLE
Show thumbnail in "Choose a map" screen when starting new game

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#3711] opened 2020-02-22 19:11 UTC
It would be really helpful for the "Choose a map" screen to show a thumbnail of a map. Oftentimes I'm looking for a map that I know the shape of, but cannot remember it's name :-)

The right-pane map metadata would need to be juggled or re-implemented to provide a space for this. Perhaps a semi-sticky tab for the right-hand pane, so a user can switch between text and thumbnails, displaying the text by default. When searching for a map one could then switch to the thumbnail tab and scroll through the left list of maps and more easily identify from their huge collection.

**Comment by gunchleoc** [comment] 2020-02-22 21:31
Duplicate of https://github.com/widelands/widelands/issues/1913

**Closed as completed by gunchleoc** 2020-02-22 21:31 UTC
Labels: duplicate, enhancement
