### ISSUE TITLE
[Duplicate] Assert failure in Suggested Teams Box

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#3942] opened 2020-06-13 11:34 UTC
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
As of the "multiplayer tournament 2020" 
https://www.widelands.org/forum/topic/4847/?page=10#post-33503
i wanted to play the builtin Map "Full Moon". But when openinig it as
mutiplayer map (not in singleplayer) I get 

Assertion failed: (w >= 0), function set_desired_size, file ../src/ui_basic/panel.cc, line 313.

**To Reproduce**
1.Open Mutiplayer Lobby, host ne Game "HasiFarming"
2. Chose Map "Full Moon"
-> See error

**Expected behavior**

Works without an Issue in R20, should do so in R21, too.

**Version:**
 - OS: macOS Caztallina 10.15.5
 - master:r24633[3a98a0b@HEAD] amazons:r24837[75189d8@amazons]

**Comment by klaus-halfmann** [comment] 2020-06-13 11:45
[Crash.txt](https://github.com/widelands/widelands/files/4774523/Crash.txt)
* Not reroducible by WorldSavior :\
* Does not depend on multi/vs single Monitor?
* Does not happen with https://www.widelands.org/maps/full-moon-11

**Comment by Noordfrees** [comment] 2020-06-13 11:48
Duplicate of #3928 
Just use a release build for now…

**Closed as completed** 2020-09-29 08:23 UTC
Labels: bug, duplicate
