### ISSUE TITLE
Unknown map object type 'ashes' Lua error when starting new game

### ISSUE THREAD

**Issue by akupar** [widelands/widelands#5301] opened 2022-03-13 12:59 UTC
**Describe the bug**
A Lua error "Unknown map object type 'ashes'" when starting a new game in the current master branch. The error occurs when the game is loading resources.

**To Reproduce**
1. Clone 'master' branch.
2. Compile
3. Start the game
4. Start a new game: single player > new game etc.

**Expected behavior**
New game should start. No error should occur.

**Screenshots**
![unknown map object type ashes](https://user-images.githubusercontent.com/49523197/158060539-d157936b-1983-47fd-b89e-57465b7bd1f9.png)

**Version:**
 - OS: Ubuntu 20.04.4 LTS
 - Widelands Version: 4131a2c1dff43e2033e25e4f2b33a475e87547a3

**Comment by Noordfrees** [comment] 2022-03-13 13:01
Duplicate of #5294 and #5295

**Closed as completed** 2022-03-21 17:41 UTC
Labels: bug, duplicate
