### ISSUE TITLE
emp03: message box layout problem with picture

### ISSUE THREAD

**Issue by s-tdh** [widelands/widelands#3997] opened 2020-07-18 22:14 UTC
In the third Empire campaign scenario, there's a message with an extra picture on the right hand side.  It's partially hidden by the scroll bar (at least in Dutch):
![messagebox_layout](https://user-images.githubusercontent.com/67842810/87862852-fe05b480-c943-11ea-82ae-8dca81f9547b.png)

**Comment by hessenfarmer** [comment] 2020-07-19 20:28
what was your screen resolution in this case?

**Comment by gunchleoc** [comment] 2020-07-20 06:41
This might be related to different text length from the translation.

**Comment by hessenfarmer** [comment] 2020-07-20 11:18
yes it seems as if due to the text length the scroll bar is blocking the picture. However the text doesn't seem to bee too long. Will have a look into this.

**Comment by hessenfarmer** [comment] 2020-07-22 11:00
Ok this is not as trivial as it looks like. The issue is that the windowheight is fixed with 500 due to support of 800x600 resolution. The 2 pictures together with formatting of headlines result in more then this height irrespective of the text so the scrollbar will always be present. To make it worse the picture of the artifacts is always aligned left, due to implementation of the objective box.    
Any ideas?   
only one I can come up with is reducing size of the image(s) or to remake the artifact image in landscape orientation

**Closed as completed** 2020-07-23 07:27 UTC
Labels: bug, internationalization, ui
