### ISSUE TITLE
memory access error

### ISSUE THREAD

**Issue by spth** [widelands/widelands#4251] opened 2020-09-10 19:27 UTC
I compiled widelands from current git on my Debian GNU/Linux testing on amd64 system, played for a while; then wiedleands crashed with memory access error.

I can reproduce the issue when loading a savegame and just letting widelands run for a few seconds:

~~~~
[04:23:54.196 game] INFO:  AI  8: 0 basic buildings in savegame file. 
[04:23:54.196 game] DEBUG:  AI 8: frisians_charcoal_burners_house strictly requires supporters
[04:23:54.196 game] DEBUG:  AI 8: frisians_collectors_house strictly requires supporters
[04:23:54.196 game] DEBUG:  AI 8: frisians_beekeepers_house strictly requires supporters
[04:23:54.196 game] DEBUG:  AI 8: frisians_aqua_farm strictly requires supporters
[04:23:54.196 game] DEBUG:  8: expedition max duration = 8100 (135 minutes), map area root: 192
[04:23:54.519 game] DEBUG: TI(6874): destination disappeared or economy mismatch -> fail
[00:00:11.149 real] INFO: Songset: Loaded song "music/ingame_10.ogg"
[04:23:58.483 game] INFO: Forcing flag at (146, 141)
Speicherzugriffsfehler
~~~~

Savegame at http://www.colecovision.eu/stuff/widelands-crash/

**Comment by Noordfrees** [comment] 2020-09-10 19:53
I cannot reproduce. Which version exactly? Did you do anything special (like open the message menu)?

**Comment by spth** [comment] 2020-09-10 20:03
I'm now also having trouble reproducing this. I've just loaded the savegame 10 times. Sometimes opening the message window, sometimes opening the minimap, sometimes building a flag to the lower right of the watchtower, sometimes also connecting that flag to the flag at the tower.

Out of that 10 times it crashed twice. But I'm still not sure what makes the difference between crashing and not crashing.
But each time the crash happened within a second of the expedition becoming ready.

**Comment by spth** [comment] 2020-09-10 20:06
I can reproduce it now:

Open message window immediately after loading the savegame, then wait until expedition is ready, then immediately click on the expedition message in the message window.

**Comment by Noordfrees** [comment] 2020-09-10 20:12
Duplicate of #4210 then

**Closed as completed** 2020-09-11 10:27 UTC
Labels: bug, duplicate, crashes or hangs
