### ISSUE TITLE
Options screen freezes graphics

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4334] opened 2020-10-10 08:57 UTC
My computer does not like the options screen since the resolution dropdown was reworked. It will often (but not always) freeze my MATE desktop to the point where I can move the mouse but do nothing else except kill my system with the power button.

**Comment by Niektory** [comment] 2020-10-10 09:03
Uh, that's bad. Does it only happen in the options screen? Immediately after opening it or after a while?

**Comment by gunchleoc** [comment] 2020-10-10 09:27
Yes, only on the options screen. The screen doesn't show at all, it freezes when I hit the button.

I'm still catching up - it might have been fixed with https://github.com/widelands/widelands/pull/4321 - I was not on the master branch.

My graphics are a bit wonky sometimes and I get freezes from other programs, but until recently Widelands was fine once I had started it successfully once. There might be an SDL bug somewhere - I can't tell at this point.

**Comment by Noordfrees** [comment] 2020-10-13 09:46
Does this still happen? I cannot reproduce (Ubuntu MATE 20.04). If yes, please run in gdb and create a backtrace while it's frozen

**Comment by gunchleoc** [comment] 2020-10-14 08:11
I can't create a backtrace when it's frozen, because everything is frozen, including typing something into GDB.

I'll have to debug this by uncommenting code, then running widelands with logging into logfile, kill and start my operating system when it freezes, rinse and repeat until I find the line that's causing it. I haven't had time for that yet.

**Comment by Noordfrees** [comment] 2020-10-14 08:23
I'm getting a total freeze on my Ubuntu MATE like every half hour ever since the upgrade to 20.04. And from what I read on the Internet lots of people have that issue, with the problem occurring randomly. For me, they usually happen while the compiler is running, never yet in Widelands. So I would guess it's not related to Widelands at all

**Comment by Niektory** [comment] 2020-10-14 08:31
If the mouse still moves then the system might be recoverable. Does switching TTYs with `Ctrl+Alt+F1...F7` work? Or at least `Ctrl+Alt+SysRq,R,E,I,S,U,B` for a gentler reboot.

**Comment by gunchleoc** [comment] 2020-10-14 11:15
It's definitely a general graphics problem on my system, but it wasn't triggered until the recent changes to the options screen so I want to investigate this when I have time. Others might have the same buggy type of system.

**Comment by gunchleoc** [comment] 2020-10-17 05:46
I have created a branch with more log output, but the crash doesn't reproduce today. Will keep trying.

**Comment by gunchleoc** [comment] 2020-10-21 03:14
It reproduced today. I annotated it like this:

log_dbg("Filling resolution dropdown");

```
// Fill in data
// Interface options
for (int modes = 0; modes < SDL_GetNumDisplayModes(0); ++modes) {
  log_dbg("Modes %d", modes);
  SDL_DisplayMode mode;
  SDL_GetDisplayMode(0, modes, &mode);
  if (kMinimumResolutionW <= mode.w && kMinimumResolutionH <= mode.h &&
      (SDL_BITSPERPIXEL(mode.format) == 32 || SDL_BITSPERPIXEL(mode.format) == 24)) {
    ScreenResolution this_res = {
       mode.w, mode.h, static_cast<int32_t>(SDL_BITSPERPIXEL(mode.format))};
    if (this_res.depth == 24) {
      this_res.depth = 32;
    }
    if (resolutions_.empty() || this_res.xres != resolutions_.rbegin()->xres ||
        this_res.yres != resolutions_.rbegin()->yres) {
      resolutions_.push_back(this_res);
    }
  }
}

log_dbg("Current res");
```

And the last log output I get it ""Filling resolution dropdown""

I'll try checking the return code from `SDL_GetNumDisplayModes(0)` to see if I can catch it and report back when this gets triggered again.

**Comment by gunchleoc** [comment] 2020-11-04 13:57
`SDL_GetNumDisplayModes(0)` itself causes the hang, so I don't know whether we can do anything about this.

**Comment by jmoerschbach** [comment] 2022-03-12 16:23
I am in favor of closing this @Noordfrees

**Closed as completed** 2022-03-12 16:41 UTC
Labels: wontfix
