### ISSUE TITLE
Crash if new game was started, savegame loading don't crash

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#5295] opened 2022-03-04 12:15 UTC
> terminate called after throwing an instance of 'WException'
>   what():  [/home/solus/Git/widelands/src/logic/map_objects/description_manager.cc:63] DescriptionManager stack not in order
> Abgebrochen (Speicherabzug geschrieben)
>

**Comment by Noordfrees** [comment] 2022-03-04 12:22
Duplicate of #5294

**Closed as completed** 2022-03-21 17:41 UTC
Labels: bug, duplicate
