### ISSUE TITLE
Multiplayer Player selection vanishes

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4217] opened 2020-09-05 07:40 UTC
Just taken from: https://github.com/widelands/widelands/pull/4188#issuecomment-686394531

> The player configuration in multiplayer selection screen does not properly. After clicking on the player type selection, the row vanishes. By removing the changes in box.cc of this PR everything works fine.

**To Reproduce**
1. Start Multiplayer LAN game and choose a map
2. Click on one of the entries 'Type: Open' (the green arrow) and apply a KI
3. The line vanishes

**Screenshots**
A 4 players map and slot 2 and 4 vanished:

![mp_vanished_lines](https://user-images.githubusercontent.com/6730556/92300496-8b847e80-ef5b-11ea-871a-54eacd181382.png)

**Version:**
 - OS: archlinux
 - Widelands Version: [a9fb8ff@master] (Debug)

**Comment by gunchleoc** [comment] 2020-09-06 08:27
Not related to the multithreading branch

**Comment by Noordfrees** [comment] 2020-09-07 07:37
Happens also in the shipwindow of an expedition ship. General UI::Box issue?

**Comment by jmoerschbach** [comment] 2020-09-07 19:43
this is caused by ignoring invisible items while calculating how much space is needed. I will take a closer look tomorrow

**Comment by jmoerschbach** [comment] 2020-09-09 19:17
Hmm, I don't really understand what the real issue is, at least regarding the bug in multiplayer setup screen. However, once #3847 is merged, this is irrelevant - on that branch the issue does not exist.
Until then, I would revert the UI::Box modification so MP games are playable on master or what do you think? @gunchleoc @frankystone @Noordfrees 

Anyways, I will check in more detail what the problem is in the shipwindow, so we might reintroduce the UI::Box modification

**Comment by jmoerschbach** [comment] 2020-09-10 19:30
I have a fix for the shipwindow issue locally on my machine

**Closed as completed** 2020-09-11 10:35 UTC
Labels: bug, tribes, ui
