### ISSUE TITLE
AI player builts shipyard on wrong places

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#4967] opened 2021-06-21 10:42 UTC
If there is a small lake or pond near the starting position, the AI player will often build the shipyard there and not by the sea.
It is particularly noticeable on the map of Europe at starting positions 4 (Turkey), 5 (Russia) and 7(French).
![Bildschirmfoto vom 2021-06-21 12-34-42](https://user-images.githubusercontent.com/37956046/122748977-146f6b00-d28d-11eb-9a42-9fb6e0422a74.png)
![Bildschirmfoto vom 2021-06-21 12-34-27](https://user-images.githubusercontent.com/37956046/122748986-16392e80-d28d-11eb-9957-fcfa89d16239.png)

My proposed solution would be for the AI to wait until a port has been built while building the shipyard and then place the shipyard right next to it. This has the additional advantage that the transport of wares to the shipyard is optimized, since the port is also a warehouse at the same time. Because shipbuilding requires a continuous flow of building materials. If a single waretype is missing, the ship will no longer be built, although all other commodities are available.

**Comment by Noordfrees** [comment] 2021-06-21 11:39
Duplicate of #1006

**Closed as completed by Noordfrees** 2021-06-21 11:39 UTC
Labels: bug, duplicate, ai
