### ISSUE TITLE
Forcing a construction site uses wrong images

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4659] opened 2021-02-06 11:03 UTC
When placing a new building per [place_building](https://www.widelands.org/documentation/autogen_wl_bases/#wl.bases.PlayerBase.place_building) and forcing a construction site some construction sites are shown with a buildings image. This happens when placing construction sites for _upgraded_ buildings.

E.g.: Placing a construction site of an empire sentry will immediately show the image of an empire barracks on the map.

Attached a small scenario where construction sites of most military buildings were set. This produces the following:

![cs_bug](https://user-images.githubusercontent.com/6730556/107116221-fbcc5e80-6871-11eb-9621-9d0fcdf1af14.jpg)

On the left are construction sites for upgraded buildings, on the right are construction sites for base buildings. The construction sites on the left side should be shown like the construction sites on the right side.

**To Reproduce**
1. Start the attached scenario

**Expected behavior**
All construction sites should use the same image.

**Version:**
 - OS: archlinux
 - Widelands Version: [3031c3f@3849_win_conditions] (Debug)
 
[test_cs_bug.zip](https://github.com/widelands/widelands/files/5936695/test_cs_bug.zip)

**Comment by Noordfrees** [comment] 2021-02-06 12:19
Duplicate of #3356?

**Comment by frankystone** [comment] 2021-02-06 13:26
Yes. So an old bug :-D

**Comment by hessenfarmer** [comment] 2023-04-19 08:05
I started digging into this, but not yet fully succesful. However the solution might not be too obvious as we have multiple cases here.
1. buildings that are pure upgrades like the empire_castle. 
2. buildings that can be build directly too like the sentry or the barrier

In #3356 it was only about the second case, where it was demanded to place a csite for the building rather then an upgrade csite. But how about placing such a csite over e.g. an outpost. in this case we should show and calculate the upgrade only. 

and for case 1 you only can force such csites currently as the building can't be build directly. So what would be the solution.

I would propose to check whether a building that can be enhanced exists at the location and place an upgrade site like at the moment. If there is no upgradeable building we should place a csite of the base building and immediately upgrade the csite as this is possible since a couple of month. So if you really want to achieve what is now the case with empire_castle you would need to place the base building first and place an upgrade csite afterwards. 
would this be an acceptable Solution @frankystone

**Closed as completed** 2023-04-22 16:03 UTC
Labels: bug, duplicate, lua, campaigns & scenarios
