### ISSUE TITLE
Bumpy two-finger scrolling

### ISSUE THREAD

**Issue by Ordoviz** [widelands/widelands#4632] opened 2021-01-17 22:46 UTC
If you drag diagonally down with two fingers on a touchpad, the scroll bar bumps back. In the recording, you can see me scrolling straight up and down like a robot first and then scrolling diagonally like I usually do because it’s a more ergonomic movement:

https://user-images.githubusercontent.com/37733333/104857695-2336a800-5912-11eb-9cb5-9c308ed96db3.mp4

**To Reproduce**
Open a window with a long text, e.g. by pressing <kbd>f1</kbd> and selecting "Controls" in the Tribal Encyclopedia.

**Expected behavior**
Scrolling should always be smooth. Interestingly, scrolling diagonally up works as expected.

**Context and version:**
I saw the announced feature freeze and downloaded [widelands-git][1] from the AUR. Version 1.0~git 291c2e310ee4bb270b3a057353198afc04187e31

[1]: https://aur.archlinux.org/packages/widelands-git

**Comment by klaus-halfmann** [comment] 2021-01-18 05:45
Thanks for your Bugreport,

we have only a few developers and I am not sure if we have the +/- same hardware around.
Please Provide Operationg System (Windows / MacOS / Linux) and for Win/Linux the hardware
used.

How does it behave when scolling in the main Game? How does it work in Longer texsts,
e.g. the Onlne Help? I assume you are not totally blocked playing the game at all?

Widelands will react to Mouse-Like Events and does not know about Trackpads as such.
So I assume our homegrown Eventhanling will get some extra events the wrong way.
I will try to reproduce this on a trackpad on macOS.
I found this at the end of the scrollbars, but difficult to reproduce.
Will try to rproduce this with some short texts later.
Looks like this happens only if the scrolling Area is quite short.

**Comment by Ordoviz** [comment] 2021-01-18 07:48
> I assume you are not totally blocked playing the game at all?

Of course not. It’s a minor inconvenience.

> I found this at the end of the scrollbars. Looks like this happens only if the scrolling Area is quite short.

That’s what I used to think as well, but it also happens at the top/middle and when the scrolling area is long. Zooming in and out on the overworld works as expected.

I use Arch Linux on a HP EliteBook 8570p.

**Comment by tothxa** [comment] 2022-09-27 13:28
I've just came across this bug report. Though I couldn't watch the video, I am able to reproduce the bug in 1.0, and checked that it is fixed by the new mousewheel handling changes in 1.1~. The cause of the bug was that the old code only checked for negative y, and treated everything else (ie. all x scroll events) as positive y.

So, fixed by #5068 (0607319)

**Closed as completed by tothxa** 2022-09-27 13:28 UTC
Labels: bug
