### ISSUE TITLE
Naval Warefare: Crash in Widelands::ShipFleet::remove_ship

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5990] opened 2023-07-04 10:32 UTC
Conquering the last HQ with HQ-Hunter wincondition the game crashes with:

~~~~
Thread 12 "widelands" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcd5906c0 (LWP 25899)]
0x000055555619cc5a in Widelands::ShipFleet::remove_ship (this=0x555558a00fd0, egbase=..., 
    ship=0x7fff9a9df020)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/economy/ship_fleet.cc:469
469                             Flag& base = ports_[0]->base_flag();
(gdb) bt
#0  0x000055555619cc5a in Widelands::ShipFleet::remove_ship (this=0x555558a00fd0, egbase=..., 
    ship=0x7fff9a9df020)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/economy/ship_fleet.cc:469
#1  0x0000555555f4b5c7 in Widelands::Ship::cleanup (this=0x7fff9a9df020, egbase=...)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/logic/map_objects/tribes/ship.cc:245
#2  0x0000555555eec48c in Widelands::MapObject::remove (this=0x7fff9a9df020, egbase=...)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/logic/map_objects/map_object.cc:538
#3  0x0000555555eef02d in Widelands::MapObject::destroy (this=0x7fff9a9df020, egbase=...)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/logic/map_objects/map_object.cc:554
#4  0x0000555556231129 in LuaMaps::LuaMapObject::destroy (this=0x7fff98af8c40, 
    L=0x55555b5622e8)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/scripting/lua_map.cc:4759
#5  0x000055555627d379 in method_dispatch<LuaMaps::LuaShip, LuaMaps::LuaMapObject> (
    L=0x55555b5622e8)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/scripting/luna_impl.h:176
#6  0x0000555556411e89 in luaD_precall (L=0x55555b5622e8, func=0x55555ba89740, nresults=0)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/third_party/eris/ldo.c:434
#7  0x000055555643171b in luaV_execute (L=0x55555b5622e8)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/third_party/eris/lvm.c:1134
#8  0x0000555556412a95 in unroll (L=0x55555b5622e8, ud=0x0)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/third_party/eris/ldo.c:556
#9  0x000055555641294a in resume (L=0x55555b5622e8, ud=0x7fffcd58f844)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/third_party/eris/ldo.c:643
#10 0x000055555641131d in luaD_rawrunprotected (L=0x55555b5622e8, f=0x555556412820 <resume>, 
    ud=0x7fffcd58f844)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/third_party/eris/ldo.c:142
#11 0x000055555641267b in lua_resume (L=0x55555b5622e8, from=0x0, nargs=0)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/third_party/eris/ldo.c:664
#12 0x0000555556362a16 in LuaCoroutine::resume (this=0x5555573d9ba0)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/scripting/lua_coroutine.cc:83
#13 0x00005555561f2825 in Widelands::CmdLuaCoroutine::execute (this=0x7fff9b349840, game=...)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/logic/cmd_luacoroutine.cc:39
#14 0x00005555561f42b3 in Widelands::CmdQueue::run_queue (this=0x55555754a4f0, interval=..., 
    game_time_var=...)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/logic/cmd_queue.cc:121
#15 0x0000555555a4a7f6 in Widelands::Game::think (this=0x555557549ba0)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/logic/game.cc:872
#16 0x0000555555ce5fcf in InteractiveBase::game_logic_think (this=0x55555728a040)
    at /home/kaputtnik/Quellcode/widelands-repo/widelands/src/wui/interactive_base.cc:874
--Type <RET> for more, q to quit, c to continue without paging--q
Quit
~~~~

**To reproduce**
1. Load this save game: [crash_remove_ship.zip](https://github.com/widelands/widelands/files/11948094/crash_remove_ship.zip)
2. The enemy has one ship in the west of the view (i guess this causes the crash)
3. Attack the green headquarter
4. Close after conquering the game crashes

**Version:**
 - OS: archlinux
 - Widelands Version: 1.2~git26244 (e52bb4c@HEAD) Debug

**Comment by Noordfrees** [comment] 2023-07-04 10:34
Looks like a duplicate of #5965 (fixed recently in #5966)

**Closed as completed** 2023-07-04 11:14 UTC
Labels: bug, duplicate
