### ISSUE TITLE
Level 2 Barbarians Campain Crash after killing the first enenmy

### ISSUE THREAD

**Issue by Only4us** [widelands/widelands#5333] opened 2022-03-27 14:55 UTC
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
After i kill the first enemy, doesn't matter which one first, in Level 2 of the Barbarians campaign the game crashes without any error message.

**To Reproduce**
1. Level 2 Barbarians campaign
2. Kill one enemy
3. wait 2 seconds
4. game switches off completely

**Expected behavior**

**Screenshots**

**Version:**
 - OS: MXlinux Kernel: 5.10.0-12-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1
 - Widelands Version: 1.1~git25627[8275fa9@master] (Release)

**Additional context**

**Comment by frankystone** [comment] 2022-03-27 16:37
Can you please provide a savegame?

**Comment by hessenfarmer** [comment] 2022-03-27 18:19
It may be the case that this was related to the postloading issues that had been fixed recently.
@Only4us can you confirm this with the latest master?

**Comment by Only4us** [comment] 2022-03-28 18:34
Where do i find the savegames on my file system?

**Comment by hessenfarmer** [comment] 2022-03-28 19:05
there should be a folder like /.widelands

**Comment by frankystone** [comment] 2022-03-30 15:57
I have played the tutorial with current master and found no crash.

You can find savegames either in `~/.widelands` or in `~/.local/share/widelands`.

**Comment by hessenfarmer** [comment] 2022-04-01 09:28
@Only4us can you confirm the crash is gone in latest master, so we can close this?

**Comment by Only4us** [comment] 2022-04-02 10:45
I found widelands under /var/lib/flatpak/app/, but i was not able to find the savegames in there. I just installed widelands recently, do i have the latest master?

**Comment by tothxa** [comment] 2022-04-02 15:31
@Only4us So you have Widelands installed as a flatpak.

Your savegames should be in `~/.var/app/org.widelands.Widelands/.widelands/save/` (`~` means your home directory).

Did you install it from flathub or flathub-beta? The command `flatpak list` shows which version you have, and where you installed it from.

**Comment by tothxa** [comment] 2022-04-02 15:41
@Only4us Your version in the original post seems to match the one used in the previous beta flatpak, so you may have that. Please try updating it to the newer one with `flatpak update org.widelands.Widelands` (or `flatpak update org.widelands.Widelands//beta` if you also have stable installed), and let us know if it still has the problem.

**Comment by hessenfarmer** [comment] 2023-04-19 07:39
closing as it was not reproducible and no further information was provided by @Only4us since over a year

**Closed as completed by hessenfarmer** 2023-04-19 07:39 UTC
Labels: bug, wontfix, non-reproducable
