### ISSUE TITLE
Widelands master fails to start with frisians/images/flag_0.5_pc.png: Unknown pixel format on macOS

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5479] opened 2022-07-30 13:04 UTC
Please fill out the relevant sections below and delete the rest.

**Describe the bug**

Just compiled widelands on macOS and got this:

libc++abi: terminating with uncaught exception of type ImageLoadingError: [.../src/graphic/image_io.h:40] Error loading tribes/initialization/frisians/images/flag_0.5_pc.png: Unknown pixel format

**To Reproduce**

* Compile
* start

please note the failure to read the config file, maybe some new macOS security feature has kicked in?

**Version:**
 - OS: macOS Monterey Versiion 12.5 (21G72)
 - Widelands Version: 1.1~git25822 (5750147@master)

using homebrew 

**Additional context**

* See [Crash.txt](https://github.com/widelands/widelands/files/9226514/Crash.txt)
* Version 1.0 has no such Issues
* removing config or .widelands directory did not help
* 
Will try a nightly build, or such, next.

**Comment by frankystone** [comment] 2022-07-30 13:12
Possibly duplicate of #5469

**Comment by klaus-halfmann** [comment] 2022-07-30 13:12
Some Version from https://github.com/widelands/widelands/releases/download/latest/Widelands-daily-debug-clang.dmg
shows the same Problem 
Did I miss some switch in Libraries latest?

**Comment by klaus-halfmann** [comment] 2022-07-30 13:21
@frankystone indeed I am on sdl2_image 2.6.0 
brew info sdl2_image
sdl2_image: stable 2.6.0 (bottled), HEAD
Library for loading images as SDL surfaces and textures
https://github.com/libsdl-org/SDL_image
/opt/homebrew/Cellar/sdl2_image/2.6.0 (12 files, 450.5KB) *
  Poured from bottle on 2022-07-19 at 17:40:38
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/sdl2_image.rb
License: Zlib

will go back to 2.5.0 ...

**Comment by klaus-halfmann** [comment] 2022-07-31 10:14
brew does not allow me to go back :-(

**Comment by Noordfrees** [comment] 2022-08-01 18:13
Closing as duplicate of #5469

**Closed as not planned by Noordfrees** 2022-08-01 18:13 UTC
Labels: duplicate
