### ISSUE TITLE
Absturz während navalwarfare Netzwerkspiel (Gleitkomma)

### ISSUE THREAD

**Issue by carli2** [widelands/widelands#6227] opened 2023-11-14 17:57 UTC
# Autogenerated crash report for 1 crash(es):

- 2023-11-14T18.55.14.txt

## Technical report:
> Version: 1.2~git26475 (00bc2d8@protected/navalwarfare) Release  
> Operating System: Linux  
> Compiled with SDL version: 2.0.20  
> SDL video driver: x11  
> Locale: de_DE.UTF-8  
> Home Directory: /home/carli/.widelands  
> Configuration File: /home/carli/.widelands/config  
> Data Directory: /home/carli/projekte/widelands/data  
> Locale Directory: /home/carli/projekte/widelands/data/locale  
> Executable Directory: /home/carli/projekte/widelands/  

## crash/2023-11-14T18.55.14.txt

```
Crash report for Widelands 1.2~git26475 (00bc2d8@protected/navalwarfare) Release at 2023-11-14T18.55.14, signal 8 (Gleitkomma-Ausnahme)

**** BEGIN BACKTRACE ****
/lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e)[0x7fbfe6045c0e]
./widelands(+0x6f2dd3)[0x55f869a0fdd3]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fbfe3442520]
./widelands(_ZN2UI22AbstractTextInputPanel6layoutEv+0x8b)[0x55f869e746eb]
./widelands(_ZN2UI3Box16update_positionsEv+0x43f)[0x55f869e1082f]
./widelands(_ZN2UI3Box6layoutEv+0x856)[0x55f869e23456]
./widelands(_ZN2UI3Box19update_desired_sizeEv+0x49d)[0x55f869e0fa5d]
./widelands(_ZN2UI3Box3addEPNS_5PanelENS0_8ResizingENS_5AlignE+0x2c8)[0x55f869e16d28]
./widelands(_ZN21QuickNavigationWindow7rebuildEv+0x1adc)[0x55f86a09144c]
./widelands(_ZN21QuickNavigationWindowC1ER15InteractiveBaseRN2UI12UniqueWindow8RegistryE+0x1514)[0x55f86a086e74]
./widelands(+0xd0415e)[0x55f86a02115e]
./widelands(_ZN15InteractiveBase10handle_keyEb10SDL_Keysym+0x52d)[0x55f86a01c6ad]
./widelands(_ZN19InteractiveGameBase10handle_keyEb10SDL_Keysym+0x140)[0x55f86a043b80]
./widelands(_ZN17InteractivePlayer10handle_keyEb10SDL_Keysym+0x50b)[0x55f86a0697bb]
./widelands(_ZN2UI5Panel6do_keyEb10SDL_Keysym+0x343)[0x55f869e57273]
./widelands(_ZN13WLApplication12handle_inputEPK13InputCallback+0xbde)[0x55f869a1bd8e]
./widelands(_ZN2UI5Panel6do_runEv+0x1241)[0x55f869e70741]
./widelands(_ZN9Widelands4Game3runENS0_13StartGameTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0x1676)[0x55f869c79b06]
./widelands(_ZN8GameHost12run_callbackEv+0x2c85)[0x55f869d69965]
./widelands(_ZN6FsMenu9LaunchMPG10clicked_okEv+0x277)[0x55f869eba3d7]
./widelands(+0x819de5)[0x55f869b36de5]
./widelands(_ZN2UI6Button19handle_mousereleaseEhii+0x169)[0x55f869e12789]
./widelands(_ZN2UI5Panel15ui_mousereleaseEhii+0x17f)[0x55f869e5e2df]
./widelands(_ZN13WLApplication12handle_inputEPK13InputCallback+0x708)[0x55f869a1b8b8]
./widelands(_ZN2UI5Panel6do_runEv+0x1241)[0x55f869e70741]
./widelands(_ZN6FsMenu8MainMenu9main_loopEv+0xce)[0x55f869eeb4be]
./widelands(_ZN13WLApplication3runEv+0x3d5)[0x55f869a2e6e5]
./widelands(main+0x1d6)[0x55f8698b85c6]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fbfe3429d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fbfe3429e40]
./widelands(_start+0x25)[0x55f869a0d7e5]
**** END BACKTRACE ****
```

**Comment by tothxa** [comment] 2023-11-14 19:22
This looks like a duplicate of #6213, which has just been fixed in master by #6218.

**Closed as completed** 2023-11-14 19:25 UTC
Labels: bug, duplicate
