### ISSUE TITLE
Assertion failed when destroying opponent HQ in multiplayer

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#5809] opened 2023-03-11 02:04 UTC
Tested with 1.2~git26073 (e082880@master) Debug on Ubuntu 20.04 and Windows 10. Save game and reply attached.

When the yellow player's HQ at coordinates 142,182,4 is destroyed in a multiplayer game, the game crashes. Sometimes the server, other times the client.

`../src/logic/playersmanager.cc:97: void Widelands::PlayersManager::add_player_end_status(const Widelands::PlayerEndStatus&, bool): Assertion 'status.player > 0 && status.player <= number_of_players_' failed.`

**To reproduce**
1. [Download](https://www.widelands.org/maps/new-england/) the "New England" map.
1. Start a LAN/direct multiplayer game with the attached save. You do not need additional players to join.
2. The yellow HQ has been (or will soon be) destroyed. Wait for 10 seconds or so.
3. Game crashes.
[assertion_failed_bug.zip](https://github.com/widelands/widelands/files/10947337/assertion_failed_bug.zip)

**Comment by hessenfarmer** [comment] 2023-03-11 14:26
probably a duplicate of #5667

**Closed as completed** 2023-03-28 18:52 UTC
Labels: bug
