### ISSUE TITLE
Assertion `it != soldiers_.end()' failed.

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5596] opened 2022-10-08 05:20 UTC
I couldn't load the attached save game because this assertion get triggered:

 ~~~~
widelands: /home/kaputtnik/Quellcode/widelands-repo/widelands/src/wui/attack_window.cc:501: void AttackWindow::ListOfSoldiers::remove(const Widelands::Soldier *): Assertion `it != soldiers_.end()' failed.
~~~~

**To Reproduce**
1. Try to load attached savegame

Running with `--verbose` gives this output:

~~~~
$:> ./widelands --verbose
This is Widelands version 1.1~git25864 (b301eaa@HEAD) Debug
[00:00:00.000 real] INFO: Set home directory: /home/kaputtnik/.widelands
[00:00:00.000 real] INFO: Set configuration file: /home/kaputtnik/.widelands/config
[00:00:00.001 real] INFO: Widelands executable directory: /home/kaputtnik/Quellcode/widelands-repo/widelands/
[00:00:00.001 real] WARNING: No locale translations found in /home/kaputtnik/Quellcode/widelands-repo/widelands/data/locale
[00:00:00.002 real] INFO: selected language: en
[00:00:00.002 real] WARNING: No corresponding locale found
[00:00:00.002 real] WARNING:  - Set LANGUAGE, LANG and LC_ALL to 'en'
[00:00:00.002 real] WARNING:  - Set system locale to 'en_US.utf8' to make 'en' accessible to libintl
[00:00:00.053 real] INFO: Setting initializer thread.
[00:00:00.053 real] INFO: Adding directory: /home/kaputtnik/Quellcode/widelands-repo/widelands/data
[00:00:00.053 real] INFO: selected language: en
[00:00:00.053 real] WARNING: No corresponding locale found
[00:00:00.053 real] WARNING:  - Set LANGUAGE, LANG and LC_ALL to 'en'
[00:00:00.054 real] WARNING:  - Set system locale to 'en_US.utf8' to make 'en' accessible to libintl
[00:00:00.058 real] INFO: Byte order: little-endian
[00:00:00.364 real] INFO: Graphics: Try to set Videomode 1702x977
[00:00:00.602 real] INFO: Graphics: OpenGL: Version "4.6.0 NVIDIA 515.76"
[00:00:00.602 real] INFO: Graphics: SDL_GL_RED_SIZE is 8
[00:00:00.602 real] INFO: Graphics: SDL_GL_GREEN_SIZE is 8
[00:00:00.602 real] INFO: Graphics: SDL_GL_BLUE_SIZE is 8
[00:00:00.602 real] INFO: Graphics: SDL_GL_ALPHA_SIZE is 0
[00:00:00.603 real] INFO: Graphics: SDL_GL_BUFFER_SIZE is 24
[00:00:00.603 real] INFO: Graphics: SDL_GL_DOUBLEBUFFER is 1
[00:00:00.603 real] INFO: Graphics: SDL_GL_DEPTH_SIZE is 24
[00:00:00.603 real] INFO: Graphics: SDL_GL_STENCIL_SIZE is 0
[00:00:00.603 real] INFO: Graphics: SDL_GL_ACCUM_RED_SIZE is 16
[00:00:00.603 real] INFO: Graphics: SDL_GL_ACCUM_GREEN_SIZE is 16
[00:00:00.603 real] INFO: Graphics: SDL_GL_ACCUM_BLUE_SIZE is 16
[00:00:00.603 real] INFO: Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 16
[00:00:00.603 real] INFO: Graphics: SDL_GL_STEREO is 0
[00:00:00.603 real] INFO: Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
[00:00:00.603 real] INFO: Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
[00:00:00.603 real] INFO: Graphics: SDL_GL_ACCELERATED_VISUAL is 1
[00:00:00.603 real] INFO: Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
[00:00:00.603 real] INFO: Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
[00:00:00.603 real] INFO: Graphics: SDL_GL_CONTEXT_FLAGS is 0
[00:00:00.603 real] INFO: Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
[00:00:00.603 real] INFO: Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
[00:00:00.603 real] INFO: Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
[00:00:00.603 real] INFO: Graphics: OpenGL: Double buffering enabled
[00:00:00.603 real] INFO: Graphics: OpenGL: Max texture size: 32768
[00:00:00.603 real] INFO: Graphics: OpenGL: ShadingLanguage: "4.60 NVIDIA"
[00:00:00.766 real] INFO: **** GRAPHICS REPORT ****
[00:00:00.766 real] INFO: VIDEO DRIVER GLVND x11
[00:00:00.766 real] INFO: Display #0: 1920x1080 @ 60hz SDL_PIXELFORMAT_RGB888
[00:00:00.766 real] INFO: Display #1: 1680x1050 @ 60hz SDL_PIXELFORMAT_RGB888
[00:00:00.766 real] INFO: **** END GRAPHICS REPORT ****
[00:00:00.766 real] INFO: Rebuilding texture atlas
[00:00:01.129 real] INFO: **** SOUND REPORT ****
[00:00:01.129 real] INFO: SDL version: 2.24.0
[00:00:01.129 real] INFO: SDL_mixer version: 2.6.2
[00:00:01.129 real] INFO: **** END SOUND REPORT ****
[00:00:01.148 real] INFO: Style Manager: Reading style templates took 9ms
[00:00:01.149 real] INFO: Setting logic thread.
[00:00:01.274 real] INFO: Registering the descriptions took 94ms
[00:00:01.283 real] INFO: Initializing economy serial
[00:00:01.290 real] INFO: lastserial: 0
[00:00:07.190 real] INFO: Registering the descriptions took 110ms
[00:00:07.198 real] INFO: Initializing economy serial
[00:00:11.212 real] INFO: Initializing economy serial
[00:00:11.614 real] INFO: Registering the descriptions took 96ms
[00:00:11.642 real] INFO: Game: Reading Preload Data ... 
[00:00:11.642 real] INFO: Game: Reading Map Data ... 
[00:00:11.642 real] INFO: Game: Reading Game Class Data ... 
[00:00:11.744 real] INFO: Registering the descriptions took 101ms
[00:00:12.191 real] INFO: ┏━ Loading empire
[00:00:12.191 real] INFO: ┃    Ships
[00:00:12.272 real] INFO: ┃    Immovables
[00:00:12.474 real] INFO: ┃    Wares
[00:00:12.519 real] INFO: ┃    Workers
[00:00:13.061 real] INFO: ┃    Buildings
[00:00:13.305 real] INFO: ┃    Frontiers, flags and roads
[00:00:13.308 real] INFO: ┃    Finalizing
[00:00:13.308 real] INFO: ┗━ took 1117ms
[00:00:13.314 real] INFO: ┏━ Loading atlanteans
[00:00:13.314 real] INFO: ┃    Ships
[00:00:13.377 real] INFO: ┃    Immovables
[00:00:13.409 real] INFO: ┃    Wares
[00:00:13.441 real] INFO: ┃    Workers
[00:00:13.599 real] INFO: ┃    Buildings
[00:00:13.795 real] INFO: ┃    Frontiers, flags and roads
[00:00:13.799 real] INFO: ┃    Finalizing
[00:00:13.799 real] INFO: ┗━ took 485ms
[00:00:13.871 real] INFO: Game: Reading Player Info ...
[00:00:13.932 real] INFO: Game: Calling read_complete()
[00:00:13.935 real] INFO: Reading Elemental Data ... 
[00:00:13.939 real] INFO: Reading Player Names And Tribe Data ... 
[00:00:13.939 real] INFO: Reading Port Spaces Data ... 
[00:00:13.939 real] INFO: Reading Heights Data ... 
[00:00:13.941 real] INFO: Reading Terrain Data ... 
[00:00:13.946 real] INFO: Reading Map Objects ... 
[00:00:14.097 real] INFO: Reading Player Start Position Data ... 
[00:00:14.099 real] INFO: Reading Resources Data ... 
[00:00:14.104 real] INFO: Reading Map Version Data ... 
[00:00:14.106 real] INFO: Reading Allowed Worker Types Data ... 
[00:00:14.106 real] INFO: Reading Allowed Building Types Data ... 
[00:00:14.108 real] INFO: Reading Node Ownership Data ... 
[00:00:14.109 real] INFO: Reading Flag Data ... 
[00:00:14.201 real] INFO: Reading Road Data ... 
[00:00:14.205 real] INFO: Reading Waterway Data ... 
[00:00:14.205 real] INFO: Reading Building Data ... 
[00:00:14.272 real] INFO: Reading Flagdata Data ... 
[00:00:14.274 real] INFO: Reading Roaddata Data ... 
[00:00:14.385 real] INFO: Reading Waterwaydata Data ... 
[00:00:14.387 real] INFO: Reading Buildingdata Data ... 
[00:00:14.397 real] INFO: Second and third phase loading Map Objects ... 
[00:00:16.451 real] INFO: Reading Players View Data ... 
[00:00:16.479 real] INFO: Reading Player Message Data ... 
[00:00:16.488 real] INFO: Reading Wincondition Data ... 
[00:00:16.489 real] INFO: Reading Objective Data ... 
[00:00:16.490 real] INFO: Reading Scripting Data ... 
[00:00:16.495 real] INFO: Reading map images ... 
[00:00:16.615 real] INFO: WidelandsMapLoader::load_map_complete() for 'Forest Valley Tournament version' took 2683ms
[00:00:16.615 real] INFO: Game: Reading Player Economies Info ... 
[00:00:16.617 real] INFO: Game: Reading ai persistent data ... 
[00:00:16.618 real] INFO: Game: Reading Command Queue Data ... 
[00:00:16.630 real] INFO: Game: Parsing messages ... 
[00:00:16.634 real] INFO: Game: Reading Interactive Player Data ... 
widelands: /home/kaputtnik/Quellcode/widelands-repo/widelands/src/wui/attack_window.cc:501: void AttackWindow::ListOfSoldiers::remove(const Widelands::Soldier *): Assertion `it != soldiers_.end()' failed.
Abgebrochen (Speicherabzug geschrieben)
~~~~

**Version:**
 - OS: archlinux
 - Widelands Version: 1.1~git25864 (b301eaa@HEAD) Debug

Save game: [wl_autosave_00.zip](https://github.com/widelands/widelands/files/9738451/wl_autosave_00.zip)

**Comment by Noordfrees** [comment] 2022-10-08 08:17
Duplicate of #5544

**Closed as completed** 2022-10-08 22:30 UTC
Labels: bug, duplicate, crashes or hangs, saveloading & compatibility, military, ui
