### ISSUE TITLE
test_io_filesystem fails with SIGABRT

### ISSUE THREAD

**Issue by Wegge** [widelands/widelands#4440] opened 2020-10-29 14:06 UTC
One of the tests run during build fails:

```
Running 2 test cases...
/builddir/build/BUILD/gcc-10.2.1-20201016/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1105: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&]: Assertion '!empty()' failed.
unknown location(0): fatal error: in "FileSystemTests/test_canonicalize_name": signal: SIGABRT (application abort requested)
/home/awj/Software/widelands/src/io/filesystem/test/test_filesystem.cc(62): last checkpoint: "test_canonicalize_name" test entry
/builddir/build/BUILD/gcc-10.2.1-20201016/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1105: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&]: Assertion '!empty()' failed.
unknown location(0): fatal error: in "FileSystemTests/test_canonicalize_name_home_expansion": signal: SIGABRT (application abort requested)
/home/awj/Software/widelands/src/io/filesystem/test/test_filesystem.cc(139): last checkpoint: "test_canonicalize_name_home_expansion" test entry

```

Skipping the tests during build produce an executable that fails with the same assert:

```
This is Widelands Version 1.0~git24992[307e746@master] (Debug)
[00:00:00.000 real] INFO: Set home directory: /home/awj/.widelands
[00:00:00.000 real] INFO: Set configuration file: /home/awj/.widelands/config
[00:00:00.000 real] INFO: Widelands executable directory: /home/awj/Software/widelands/
/builddir/build/BUILD/gcc-10.2.1-20201016/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1105: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&]: Assertion '!empty()' failed.
Afbrudt (SIGABRT) (smed kerne)

```

**Comment by matthiakl** [comment] 2020-10-29 15:01
Not reproducible on all systems, but should be fixed in PR #4420 
([here](https://github.com/widelands/widelands/pull/4420/files#diff-3e4b0e84aa3aa81913132bd9497c3996bc3c41a24a83ab2239d3078a89f16db0))

**Comment by frankystone** [comment] 2020-10-31 20:02
I can't reproduce:

~~~~
[ 27%] Built target wl_tests
Test project /home/kaputtnik/widelands-repo/widelands/build
    Start 1: test_ai
1/5 Test #1: test_ai ..........................   Passed    0.03 sec
    Start 2: test_economy
2/5 Test #2: test_economy .....................   Passed    0.03 sec
    Start 3: test_io_filesystem
3/5 Test #3: test_io_filesystem ...............   Passed    0.02 sec
    Start 4: notifications_test
4/5 Test #4: notifications_test ...............   Passed    0.02 sec
    Start 5: test_scripting
5/5 Test #5: test_scripting ...................   Passed    0.02 sec

100% tests passed, 0 tests failed out of 5
~~~~

Can you try to delete the build directory and compile again?

**Comment by Wegge** [comment] 2020-11-01 09:44
Building from scratch did not change things. I tried poking at it with gdb, but I'm not a C++ programmer, so unfortunately, it was gibberish to me. I have attached the backtrace here.
[test_io_filesystem.txt](https://github.com/widelands/widelands/files/5470505/test_io_filesystem.txt)

**Comment by matthiakl** [comment] 2020-11-12 10:23
Now that #4420 is in, can you please check, whether the issue does still exist in current master?

**Comment by matthiakl** [comment] 2021-01-07 21:44
> Now that #4420 is in, can you please check, whether the issue does still exist in current master?

@Wegge can you please report, whether the issue does still exist? Otherwise I can close it.

**Comment by hessenfarmer** [comment] 2021-03-01 19:21
@Wegge are you planning to report anything as asked by @matthiakl? 
If not, just tell us please so we can close the bug.

**Comment by Noordfrees** [comment] 2021-03-12 22:21
No response here, let's assume the problem no longer happens.

**Closed as completed by Noordfrees** 2021-03-12 22:21 UTC
Labels: bug, crashes or hangs
